//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ledger
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateOfSale { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string Particulars { get; set; }
        public Nullable<long> DrAmount { get; set; }
        public Nullable<long> CrAmount { get; set; }
        public Nullable<long> Balance { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
