//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseLedger
    {
        public int Id { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<double> BalanceAmount { get; set; }
        public Nullable<double> CreditAmount { get; set; }
        public Nullable<double> DebitAmunt { get; set; }
        public string Particulars { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual PurchaseInvoice PurchaseInvoice { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
