//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesInvoice
    {
        public int ID { get; set; }
        public string InvoiceId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> DateOfPurchase { get; set; }
        public Nullable<double> TotalPurchaseAmount { get; set; }
        public Nullable<double> TotalDiscount { get; set; }
        public Nullable<double> DiscountedAmount { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
