//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int id { get; set; }
        public Nullable<int> productid { get; set; }
        public string pack { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<int> CGstPercent { get; set; }
        public Nullable<int> IGSTPercent { get; set; }
        public Nullable<int> SGSTPercent { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> discountpercentage { get; set; }
        public Nullable<int> InvoiceId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual SalesInvoice SalesInvoice { get; set; }
    }
}
