//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int id { get; set; }
        public Nullable<int> productid { get; set; }
        public string pack { get; set; }
        public string quantity { get; set; }
        public string price { get; set; }
        public string rate { get; set; }
        public string CGstPercent { get; set; }
        public string IGSTPercent { get; set; }
        public string SGSTPercent { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string discountpercentage { get; set; }
        public string totalamountbeforetax { get; set; }
        public string totalamountaftertax { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
